import Head from "next/head";
import Services from "@/components/Services/Services";
import AboutUs from "@/components/AboutUs/AboutUs";
import Facts from "@/components/Facts/Facts";
import Team from "@/components/Team/Team";
import Testimonials from "@/components/Testimonials/Testimonials";
import MainBanner from "@/components/MainBanner/MainBanner";


export default function Home() {
  return (
    <>
      <Head>
        <title>Scholar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainBanner/>
      <Services />
      <AboutUs />
      <Facts />
      <Team />
      <Testimonials />
    </>
  );
}
